# If true, the coordinates are added to the death message using the
# messages setted after
# If false, a private message will be send directly to the player
public-death: true

# These messages should contain 2 ``%s`` for each message!
public-death-messages:
    block_explosion:  "%s just got blown up at %s"
    contact:          "%s rubbed a cactus at %s"
    custom:           "%s died at %s"
    drowning:         "%s drown at %s"
    entity_attack:    "%s got powned at %s"
    entity_explosion: "%s blew up at %s"
    fall:             "%s fall from too high at %s"
    falling_block:    "%s took a block on the head at %s"
    fire:             "%s burned his fingers at %s"
    fire_tick:        "%s stayed too long near the fire at %s"
    lava:             "%s found a lava lake at %s"
    lightning:        "%s got thundered at %s"
    magic:            "%s suddenly disappeared at %s"
    melting:          "%s melted? at %s"
    poison:           "%s eated something rotten at %s"
    projectile:       "%s took an arrow in the eye at %s"
    starvation:       "%s forgot to eat at %s"
    suffocation:      "%s died in a block at %s"
    suicide:          "%s killed himself at %s"
    thorns:           "%s hitted a spiky ball to much at %s"
    void:             "%s fell in the interstellar void at %s"
    wither:           "%s got owned by a wither at %s"

# This message should contain one ``%s``
# Note that the despawn message will be added after this line
private-death-message: "You died at %s."

# If true, a message will be added to know when the stuff will despawn
# Note that the message is only shown if the player drop items
show-despawn-time: true
# Send a message to the player when his items has disappeared
remind-at-despawn: true
# Default item despawn time is 5 minutes (300 seconds)
despawn-time: 300
# This message should contain one ``%s``
despawn-time-message: "You items will despawn at %s"
despawn-message: "Your items just despawned..."

# Set to false to remove the [OnDeathCoord] prefix from the chat messages
prefix-public-messages: true
prefix-private-messages: true
